{% set version = "3.2.0" %}

package:
  name: nda
  version: {{ version }}

source:
  url: https://github.com/TRIQS/nda/releases/download/{{ version }}/nda-{{ version }}.tar.gz
  sha256: PUT HERE THE SHA256 OF YOUR RELEASE TARBALL

build:
  number: 0
  skip: True  # [win or py<30]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - hdf5
    - {{ mpi }}
    - libblas
    - liblapack
    - python
  run:
    - hdf5
    - {{ mpi }}
    - libblas
    - liblapack
    - python

test:
  commands:
    - export OMPI_MCA_btl=self,tcp
    - export OMPI_MCA_plm=isolated
    - export OMPI_MCA_rmaps_base_oversubscribe=yes
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - export mpiexec="mpiexec --allow-run-as-root"
    - python -c "import nda"

about:
  home: https://triqs.github.io/nda
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'An application based on the TRIQS library'

extra:
  recipe-maintainers:
    - wentzell
    - pgunn
