/**
 * @file
 * @brief Provides lazy, coefficient-wise array operations of standard mathematical functions together with overloads
 * for nda::Scalar types.
 */

#pragma once

#include "./concepts.hpp"
#include "./map.hpp"
#include "./mapped_functions.hpp"
#include "./traits.hpp"

#include <cmath>
#include <complex>
#include <utility>

/*
   File is generated by vim.
   To regenerate the file,
     1- load the vim function by (or add this to your .vim ?)
        :source vimexpand.vim
     2- call it
        :call VimExpandSimple()


   It is better than C macro, it gives a cleaner code
   (for error messages, no preproc, doc generation : otherwise no doc string ...)

  ----  normal mapping -------

  VIMEXPAND abs imag floor
  /// \brief Function @ for nda::ArrayOrScalar types (lazy and coefficient-wise for nda::Array types).
  ///
  /// \tparam A nda::ArrayOrScalar type.
  /// \param a nda::ArrayOrScalar object.
  /// \return A lazy nda::expr_call object (nda::Array) or the result of `std::@` applied to the object (nda::Scalar).
  template <ArrayOrScalar A>
  auto @(A &&a)  {
    return nda::map(
       [](auto const &x) {
         using std::@;
         return @(x);
       })(std::forward<A>(a));
  }

 ---------  same, no using std::-------

  VIMEXPAND real abs2 isnan
  /// \brief Function @ for nda::ArrayOrScalar types (lazy and coefficient-wise for nda::Array types).
  ///
  /// \tparam A nda::ArrayOrScalar type..
  /// \param a nda::ArrayOrScalar object.
  /// \return A lazy nda::expr_call object (nda::Array) or the result of `nda::detail::@` applied to the object (nda::Scalar).
  template <ArrayOrScalar A>
  auto @(A &&a) {
    return nda::map(
       [](auto const &x) {return detail::@(x); })(std::forward<A>(a));
  }

 ---------  mapping with matrix excluded -------

  VIMEXPAND exp cos sin tan cosh sinh tanh acos asin atan log sqrt
  /// \brief Function @ for non-matrix nda::ArrayOrScalar types (lazy and coefficient-wise for nda::Array types).
  ///
  /// \tparam A nda::ArrayOrScalar type.
  /// \param a nda::ArrayOrScalar object.
  /// \return  A lazy nda::expr_call object (nda::Array) or the result of `std::@` applied to the object (nda::Scalar).
  template <ArrayOrScalar A>
  auto @(A &&a) requires(get_algebra<A> != 'M') {
    return nda::map(
       [](auto const &x) {
         using std::@;
         return @(x);
       })(std::forward<A>(a));
  }

*/

namespace nda {

  /**
   * @addtogroup av_math
   * @{
   */

  // --- VIMEXPAND_START  --DO NOT EDIT BELOW --


  /// \brief Function abs for nda::ArrayOrScalar types (lazy and coefficient-wise for nda::Array types).
  ///
  /// \tparam A nda::ArrayOrScalar type.
  /// \param a nda::ArrayOrScalar object.
  /// \return A lazy nda::expr_call object (nda::Array) or the result of `std::abs` applied to the object (nda::Scalar).
  template <ArrayOrScalar A>
  auto abs(A &&a)  {
    if constexpr (std::is_unsigned_v<get_value_t<A>>) {
      return a;
    } else {
      return nda::map([](auto const &x) {
        using std::abs;
        return abs(x);
      })(std::forward<A>(a));
    }
  }

  /// \brief Function imag for nda::ArrayOrScalar types (lazy and coefficient-wise for nda::Array types).
  ///
  /// \tparam A nda::ArrayOrScalar type.
  /// \param a nda::ArrayOrScalar object.
  /// \return A lazy nda::expr_call object (nda::Array) or the result of `std::imag` applied to the object (nda::Scalar).
  template <ArrayOrScalar A>
  auto imag(A &&a)  {
    return nda::map(
       [](auto const &x) {
         using std::imag;
         return imag(x);
       })(std::forward<A>(a));
  }

  /// \brief Function floor for nda::ArrayOrScalar types (lazy and coefficient-wise for nda::Array types).
  ///
  /// \tparam A nda::ArrayOrScalar type.
  /// \param a nda::ArrayOrScalar object.
  /// \return A lazy nda::expr_call object (nda::Array) or the result of `std::floor` applied to the object (nda::Scalar).
  template <ArrayOrScalar A>
  auto floor(A &&a)  {
    auto scalar_lambda = [](auto const &x) { return std::floor(x); };
    auto simd_lambda   = [](auto const &x) { return xsimd::floor(x); };

    return nda::map(detail::unary_functor<decltype(scalar_lambda), decltype(simd_lambda)>{})(std::forward<A>(a));
  }

  /// \brief Function real for nda::ArrayOrScalar types (lazy and coefficient-wise for nda::Array types).
  ///
  /// \tparam A nda::ArrayOrScalar type..
  /// \param a nda::ArrayOrScalar object.
  /// \return A lazy nda::expr_call object (nda::Array) or the result of `nda::detail::real` applied to the object (nda::Scalar).
  template <ArrayOrScalar A>
  auto real(A &&a) {
    return nda::map(
       [](auto const &x) {return detail::real(x); })(std::forward<A>(a));
  }

  /// \brief Function abs2 for nda::ArrayOrScalar types (lazy and coefficient-wise for nda::Array types).
  ///
  /// \tparam A nda::ArrayOrScalar type..
  /// \param a nda::ArrayOrScalar object.
  /// \return A lazy nda::expr_call object (nda::Array) or the result of `nda::detail::abs2` applied to the object (nda::Scalar).
  template <ArrayOrScalar A>
  auto abs2(A &&a) {
    return nda::map(
       [](auto const &x) {return detail::abs2(x); })(std::forward<A>(a));
  }

  /// \brief Function isnan for nda::ArrayOrScalar types (lazy and coefficient-wise for nda::Array types).
  ///
  /// \tparam A nda::ArrayOrScalar type..
  /// \param a nda::ArrayOrScalar object.
  /// \return A lazy nda::expr_call object (nda::Array) or the result of `nda::detail::isnan` applied to the object (nda::Scalar).
  template <ArrayOrScalar A>
  auto isnan(A &&a) {
    return nda::map(
       [](auto const &x) {return detail::isnan(x); })(std::forward<A>(a));
  }

  /// \brief Function exp for non-matrix nda::ArrayOrScalar types (lazy and coefficient-wise for nda::Array types).
  ///
  /// \tparam A nda::ArrayOrScalar type.
  /// \param a nda::ArrayOrScalar object.
  /// \return  A lazy nda::expr_call object (nda::Array) or the result of `std::exp` applied to the object (nda::Scalar).
  template <ArrayOrScalar A>
  auto exp(A &&a) requires(get_algebra<A> != 'M') {
    auto scalar_lambda = [](auto const &x) { return std::exp(x); };
    auto simd_lambda   = [](auto const &x) { return xsimd::exp(x); };

    return nda::map(detail::unary_functor<decltype(scalar_lambda), decltype(simd_lambda)>{})(std::forward<A>(a));
  }

  /// \brief Function cos for non-matrix nda::ArrayOrScalar types (lazy and coefficient-wise for nda::Array types).
  ///
  /// \tparam A nda::ArrayOrScalar type.
  /// \param a nda::ArrayOrScalar object.
  /// \return  A lazy nda::expr_call object (nda::Array) or the result of `std::cos` applied to the object (nda::Scalar).
  template <ArrayOrScalar A>
  auto cos(A &&a) requires(get_algebra<A> != 'M') {
    auto scalar_lambda = [](auto const &x) { return std::cos(x); };
    auto simd_lambda   = [](auto const &x) { return xsimd::cos(x); };

    return nda::map(detail::unary_functor<decltype(scalar_lambda), decltype(simd_lambda)>{})(std::forward<A>(a));
  }

  /// \brief Function sin for non-matrix nda::ArrayOrScalar types (lazy and coefficient-wise for nda::Array types).
  ///
  /// \tparam A nda::ArrayOrScalar type.
  /// \param a nda::ArrayOrScalar object.
  /// \return  A lazy nda::expr_call object (nda::Array) or the result of `std::sin` applied to the object (nda::Scalar).
  template <ArrayOrScalar A>
  auto sin(A &&a) requires(get_algebra<A> != 'M') {
    auto scalar_lambda = [](auto const &x) { return std::sin(x); };
    auto simd_lambda   = [](auto const &x) { return xsimd::sin(x); };

    return nda::map(detail::unary_functor<decltype(scalar_lambda), decltype(simd_lambda)>{})(std::forward<A>(a));
  }

  /// \brief Function tan for non-matrix nda::ArrayOrScalar types (lazy and coefficient-wise for nda::Array types).
  ///
  /// \tparam A nda::ArrayOrScalar type.
  /// \param a nda::ArrayOrScalar object.
  /// \return  A lazy nda::expr_call object (nda::Array) or the result of `std::tan` applied to the object (nda::Scalar).
  template <ArrayOrScalar A>
  auto tan(A &&a) requires(get_algebra<A> != 'M') {
    auto scalar_lambda = [](auto const &x) { return std::tan(x); };
    auto simd_lambda   = [](auto const &x) { return xsimd::tan(x); };

    return nda::map(detail::unary_functor<decltype(scalar_lambda), decltype(simd_lambda)>{})(std::forward<A>(a));
  }

  /// \brief Function cosh for non-matrix nda::ArrayOrScalar types (lazy and coefficient-wise for nda::Array types).
  ///
  /// \tparam A nda::ArrayOrScalar type.
  /// \param a nda::ArrayOrScalar object.
  /// \return  A lazy nda::expr_call object (nda::Array) or the result of `std::cosh` applied to the object (nda::Scalar).
  template <ArrayOrScalar A>
  auto cosh(A &&a) requires(get_algebra<A> != 'M') {
    auto scalar_lambda = [](auto const &x) { return std::cosh(x); };
    auto simd_lambda   = [](auto const &x) { return xsimd::cosh(x); };

    return nda::map(detail::unary_functor<decltype(scalar_lambda), decltype(simd_lambda)>{})(std::forward<A>(a));
  }

  /// \brief Function sinh for non-matrix nda::ArrayOrScalar types (lazy and coefficient-wise for nda::Array types).
  ///
  /// \tparam A nda::ArrayOrScalar type.
  /// \param a nda::ArrayOrScalar object.
  /// \return  A lazy nda::expr_call object (nda::Array) or the result of `std::sinh` applied to the object (nda::Scalar).
  template <ArrayOrScalar A>
  auto sinh(A &&a) requires(get_algebra<A> != 'M') {
    auto scalar_lambda = [](auto const &x) { return std::sinh(x); };
    auto simd_lambda   = [](auto const &x) { return xsimd::sinh(x); };

    return nda::map(detail::unary_functor<decltype(scalar_lambda), decltype(simd_lambda)>{})(std::forward<A>(a));
  }

  /// \brief Function tanh for non-matrix nda::ArrayOrScalar types (lazy and coefficient-wise for nda::Array types).
  ///
  /// \tparam A nda::ArrayOrScalar type.
  /// \param a nda::ArrayOrScalar object.
  /// \return  A lazy nda::expr_call object (nda::Array) or the result of `std::tanh` applied to the object (nda::Scalar).
  template <ArrayOrScalar A>
  auto tanh(A &&a) requires(get_algebra<A> != 'M') {
    auto scalar_lambda = [](auto const &x) { return std::tanh(x); };
    auto simd_lambda   = [](auto const &x) { return xsimd::tanh(x); };

    return nda::map(detail::unary_functor<decltype(scalar_lambda), decltype(simd_lambda)>{})(std::forward<A>(a));
  }

  /// \brief Function acos for non-matrix nda::ArrayOrScalar types (lazy and coefficient-wise for nda::Array types).
  ///
  /// \tparam A nda::ArrayOrScalar type.
  /// \param a nda::ArrayOrScalar object.
  /// \return  A lazy nda::expr_call object (nda::Array) or the result of `std::acos` applied to the object (nda::Scalar).
  template <ArrayOrScalar A>
  auto acos(A &&a) requires(get_algebra<A> != 'M') {
    auto scalar_lambda = [](auto const &x) { return std::acos(x); };
    auto simd_lambda   = [](auto const &x) { return xsimd::acos(x); };

    return nda::map(detail::unary_functor<decltype(scalar_lambda), decltype(simd_lambda)>{})(std::forward<A>(a));
  }

  /// \brief Function asin for non-matrix nda::ArrayOrScalar types (lazy and coefficient-wise for nda::Array types).
  ///
  /// \tparam A nda::ArrayOrScalar type.
  /// \param a nda::ArrayOrScalar object.
  /// \return  A lazy nda::expr_call object (nda::Array) or the result of `std::asin` applied to the object (nda::Scalar).
  template <ArrayOrScalar A>
  auto asin(A &&a) requires(get_algebra<A> != 'M') {
    auto scalar_lambda = [](auto const &x) { return std::asin(x); };
    auto simd_lambda   = [](auto const &x) { return xsimd::asin(x); };

    return nda::map(detail::unary_functor<decltype(scalar_lambda), decltype(simd_lambda)>{})(std::forward<A>(a));
  }

  /// \brief Function atan for non-matrix nda::ArrayOrScalar types (lazy and coefficient-wise for nda::Array types).
  ///
  /// \tparam A nda::ArrayOrScalar type.
  /// \param a nda::ArrayOrScalar object.
  /// \return  A lazy nda::expr_call object (nda::Array) or the result of `std::atan` applied to the object (nda::Scalar).
  template <ArrayOrScalar A>
  auto atan(A &&a) requires(get_algebra<A> != 'M') {
    auto scalar_lambda = [](auto const &x) { return std::atan(x); };
    auto simd_lambda   = [](auto const &x) { return xsimd::atan(x); };

    return nda::map(detail::unary_functor<decltype(scalar_lambda), decltype(simd_lambda)>{})(std::forward<A>(a));
  }

  /// \brief Function log for non-matrix nda::ArrayOrScalar types (lazy and coefficient-wise for nda::Array types).
  ///
  /// \tparam A nda::ArrayOrScalar type.
  /// \param a nda::ArrayOrScalar object.
  /// \return  A lazy nda::expr_call object (nda::Array) or the result of `std::log` applied to the object (nda::Scalar).
  template <ArrayOrScalar A>
  auto log(A &&a) requires(get_algebra<A> != 'M') {
    auto scalar_lambda = [](auto const &x) { return std::log(x); };
    auto simd_lambda   = [](auto const &x) { return xsimd::log(x); };

    return nda::map(detail::unary_functor<decltype(scalar_lambda), decltype(simd_lambda)>{})(std::forward<A>(a));
  }

  /// \brief Function sqrt for non-matrix nda::ArrayOrScalar types (lazy and coefficient-wise for nda::Array types).
  ///
  /// \tparam A nda::ArrayOrScalar type.
  /// \param a nda::ArrayOrScalar object.
  /// \return  A lazy nda::expr_call object (nda::Array) or the result of `std::sqrt` applied to the object (nda::Scalar).
  template <ArrayOrScalar A>
  auto sqrt(A &&a) requires(get_algebra<A> != 'M') {
    auto scalar_lambda = [](auto const &x) { return std::sqrt(x); };
    auto simd_lambda   = [](auto const &x) { return xsimd::sqrt(x); };

    return nda::map(detail::unary_functor<decltype(scalar_lambda), decltype(simd_lambda)>{})(std::forward<A>(a));
  }

  /** @} */

}
