# Configuration file. Edit the options below

skip_deprecated: true
source_file_only: false # Document only functions/classes/... in the source file, excluding indirect includes
compile_examples: false # Compile the example to check them.

includers:     # regex -> filename
  '.*': nda/nda.hpp

white_list: ['nda::.*']  
black_list: ['nda::expr.*', '.*_impl', 'nda::clef::.*'] 
ns_white_list: ['nda', 'nda::blas', 'nda::stdutil']  

# source_remote_prefix: https://github.com/triqs/nda
